name: CI Pipeline for to build and upload rock

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pack with Rockcraft
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: canonical/craft-actions/rockcraft-pack@main
      id: rockcraft
    - uses: actions/upload-artifact@v3
      with:
        name: rock
        path: ${{ steps.build-rock.outputs.rock }}
